# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '42sparta_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 42sparta_ios

	pod 'RxSwift', '~> 4.0'
	pod 'RxCocoa', '~> 4.0'

  target '42sparta_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '42sparta_iosUITests' do
    # Pods for testing
  end



end
