#Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sparta42_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for sparta42_iOS

	pod 'RxSwift', '~> 4.0'
	pod 'RxCocoa', '~> 4.0'
	pod 'RealmSwift'
  target 'sparta42_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sparta42_iOSUITests' do
    # Pods for testing
  end

end
